# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20171118_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='amount',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
