# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_auto_20171119_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='quantity',
            field=models.IntegerField(max_length=200),
        ),
    ]
