# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20171119_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(max_length=200),
        ),
    ]
